/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ItemEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import model.MailValidator;

/**
 *
 * @author t.combarieu
 */
public class AjoutDialog extends javax.swing.JDialog {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    private MailValidator mailValidator;

    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    /**
     * Creates new form AjoutDialog
     */
    public AjoutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.mailValidator = new MailValidator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JAjouter = new javax.swing.JButton();
        jTextNom = new javax.swing.JTextField();
        JNom = new javax.swing.JLabel();
        JTextIdentifiant = new javax.swing.JTextField();
        jPrenom = new javax.swing.JLabel();
        jIdentifiant = new javax.swing.JLabel();
        JTextPrenom = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        jTextPassword = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMail = new javax.swing.JFormattedTextField();
        verifPasswordFieldAdd = new javax.swing.JPasswordField();
        verifPasswordLabelAdd = new javax.swing.JLabel();
        checkboxPassword = new javax.swing.JCheckBox();
        checkboxVerif = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JAjouter.setText("Ajouter");
        JAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAjouterActionPerformed(evt);
            }
        });

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        JNom.setText("Nom :");

        JTextIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextIdentifiantActionPerformed(evt);
            }
        });

        jPrenom.setText("Prenom :");

        jIdentifiant.setText("Identifiant : ");

        JTextPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextPrenomActionPerformed(evt);
            }
        });

        jPassword.setText("Mot de passe :");

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Adresse Mail :");

        jMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailActionPerformed(evt);
            }
        });

        verifPasswordLabelAdd.setText("Vérification du mot de passe :");

        checkboxPassword.setText("Montrer le mot de passe");
        checkboxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPasswordActionPerformed(evt);
            }
        });

        checkboxVerif.setText("Montrer le mot de passe");
        checkboxVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxVerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JAjouter)
                        .addGap(65, 65, 65)
                        .addComponent(cancelButton)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(verifPasswordLabelAdd)
                            .addComponent(jIdentifiant)
                            .addComponent(jPrenom)
                            .addComponent(JNom)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jTextNom)
                            .addComponent(jMail)
                            .addComponent(jTextPassword)
                            .addComponent(JTextIdentifiant)
                            .addComponent(verifPasswordFieldAdd))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxPassword)
                    .addComponent(checkboxVerif))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNom))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrenom))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdentifiant)
                    .addComponent(JTextIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxPassword))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifPasswordFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifPasswordLabelAdd)
                    .addComponent(checkboxVerif))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAjouter)
                    .addComponent(cancelButton))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JAjouter, JNom, JTextIdentifiant, JTextPrenom, cancelButton, jIdentifiant, jLabel1, jMail, jPassword, jPrenom, jTextNom, jTextPassword, verifPasswordFieldAdd, verifPasswordLabelAdd});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void JAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAjouterActionPerformed

        listeners.firePropertyChange("validNewUser", null, null);

        // Récpérer la valeurs des champs
        //String nom = jTextNom.getText();
        //String prenom = JTextPrenom.getText();
        //String mail = jMail.getText();
        //String identifiant = JTextIdentifiant.getText();
        //String password = jTextPassword.getText();

    }//GEN-LAST:event_JAjouterActionPerformed

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void JTextPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextPrenomActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void JTextIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextIdentifiantActionPerformed

    private void jMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailActionPerformed

    private void checkboxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxPasswordActionPerformed
        if (checkboxPassword.isSelected()) {
            jTextPassword.setEchoChar((char) 0);
        } else {
            jTextPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxPasswordActionPerformed

    private void checkboxVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxVerifActionPerformed
        if (checkboxVerif.isSelected()) {
            verifPasswordFieldAdd.setEchoChar((char) 0);
        } else {
            verifPasswordFieldAdd.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxVerifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutDialog dialog = new AjoutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAjouter;
    private javax.swing.JLabel JNom;
    private javax.swing.JTextField JTextIdentifiant;
    private javax.swing.JTextField JTextPrenom;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox checkboxPassword;
    private javax.swing.JCheckBox checkboxVerif;
    private javax.swing.JLabel jIdentifiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField jMail;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jPrenom;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JPasswordField jTextPassword;
    private javax.swing.JPasswordField verifPasswordFieldAdd;
    private javax.swing.JLabel verifPasswordLabelAdd;
    // End of variables declaration//GEN-END:variables

    public String getNom() {
        return this.jTextNom.getText();
    }

    public String getPrenom() {
        return this.JTextPrenom.getText();
    }

    public String getEmail() {
        return this.jMail.getText();
    }

    public String getIdentifiant() {
        return this.JTextIdentifiant.getText();
    }

    public char[] getPassword() {
        return this.jTextPassword.getPassword();
    }

    public char[] getPasswordVerif() {
        return this.verifPasswordFieldAdd.getPassword();
    }

    public void setDefaultTextfieldData() {
        this.jTextNom.setText("");
        this.JTextPrenom.setText("");
        this.jMail.setText("");
        this.JTextIdentifiant.setText("");
        this.jTextPassword.setText("");
        this.verifPasswordFieldAdd.setText("");
        this.jTextPassword.setEchoChar('*');
        this.verifPasswordFieldAdd.setEchoChar('*');
        this.checkboxPassword.setSelected(false);
        this.checkboxVerif.setSelected(false);
    }

    public int verifForm() {
        if (JTextIdentifiant.getText().equals("")
                || jTextNom.getText().equals("")
                || JTextPrenom.getText().equals("")
                || jMail.getText().equals("")
                || String.valueOf(this.jTextPassword.getPassword()).equals("")) {
            return 1;
        } else if (!String.valueOf(this.jTextPassword.getPassword()).equals(String.valueOf(this.verifPasswordFieldAdd.getPassword()))) {
            return 2;
        } else if (!mailValidator.validate(this.getEmail().trim())) {
            return 3;
        } else {
            return 4;
        }
    }
}
